version: "3"

services:
   service:
     container_name: demo_producer
     build:
       context: .
       dockerfile: Dockerfile
     restart: on-failure
     depends_on:
       -   db
     ports:
       - 8080:8080
     environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testdemo
       SPRING_DATASOURCE_USERNAME: root123
       SPRING_DATASOURCE_PASSWORD: root
   db:
     image: "mysql:latest"
     restart: on-failure
     ports:
       - 3308:3306
     environment:
        MYSQL_USER: root123
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: testdemo
     volumes:
       - db_data:/var/lib/mysql
   pact-broker:
     image: pactfoundation/pact-broker
     restart: on-failure
     ports:
       - 9292:9292
     depends_on:
       - db
     environment:
       PACT_BROKER_DATABASE_USERNAME: root123
       PACT_BROKER_DATABASE_PASSWORD: root
       PACT_BROKER_DATABASE_HOST: db
       PACT_BROKER_DATABASE_NAME: testdemo
       PACT_BROKER_DATABASE_LOG: DEBUG
       PACT_BROKER_DATABASE_PORT: 3306
       PACT_BROKER_DATABASE_ADAPTER: mysql2

volumes:
  db_data: